### ISSUE TITLE
[BUG] API calls don't display any report definitions nor instances

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/dashboards-reporting#119]
@51CGO commented on [Wed May 24 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4125)

**Describe the bug**

When calling API .opendistro-reports-instances/_search or .opendistro-reports-definitions/_search, no hit is found.

**To Reproduce**
1. Create some reports definitions using Reporting -> Report definitions -> Create
2. Verify that the definitions exists and that some reports have been created 
3. Go to Dev tools
4. Try the following calls:
GET .opendistro-reports-instances/_search
GET .opendistro-reports-definitions/_search
=> no hit displayed

**Expected behavior**
These calls should display the definitions and the instances

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Plugins**
Standard installation without adding nor removing any plugin.

**Screenshots**
![2023-05-24 10_51_35-Window](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12408378/67fcebae-e508-4732-a661-738e73ef29b9)
![2023-05-24 10_52_12-Window](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12408378/296d9fbc-6b26-4245-958a-a6b2dc3f2860)
![2023-05-24 10_52_34-Window](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12408378/07942f78-7a89-4b38-985f-af1c1d86617a)

**Host/Environment (please complete the following information):**
 - OS: RHEL 8
 - Browser and version : Firefox 102
 

---

@zhongnansu commented on [Wed May 24 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4125#issuecomment-1561909536)

@opensearch-project/triage please help moving to reporting repo

---

@joshuarrrr commented on [Thu May 25 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4125#issuecomment-1563224143)

Thanks @51CGO - we'll get this moved to the reporting repo: https://github.com/opensearch-project/dashboards-reporting

**Comment by 51CGO** [comment]
@joshuali925 : As there is not button to delete générated reports ( see https://github.com/opensearch-project/dashboards-reporting/issues/92 ), I wanted to do it by API calls.

**Comment by nickwalchliqantas** [comment]
@joshuali925 agree, there is no button to delete or archive or manage reports in any way.. once generated they just sit there, is there a reason we can't do anything with them, seems like missing functionality, this should be reopened
