### ISSUE TITLE
[Cypress test onboarding]: Please on board to Cypress tests / E2E functional test repo

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/dashboards-reporting#171]
**Is your feature request related to a problem?**
Please onboard to functional test repo for catching dependency issues on dashboards

**Comment by anirudha** [comment]
reporting has cypress tests in functional test repo.
github: https://github.com/opensearch-project/opensearch-dashboards-functional-test/tree/main/cypress/integration/plugins/reports-dashboards
