### ISSUE TITLE
Trying to install dashboards-reports 2.2.0.0 plugin in opensearch dashboards 2.2.0 but getting error.

### ISSUE THREAD

**Issue by Rajeshdaneti** [opensearch-project/dashboards-reporting#537]
Hi All,
Trying to install dashboards-reports 2.2.0.0 plugin in opensearch dashboards 2.2.0 but getting following error-
Please assist me in solving the problem.

/usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin install https://github.com/opensearch-project/dashboards-reports/archive/refs/tags/2.2.0.0.zip
Attempting to transfer from https://github.com/opensearch-project/dashboards-reports/archive/refs/tags/2.2.0.0.zip
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No opensearch-dashboards plugins found in archive".

If I'm installing incorrectly, kindly also provide me the steps of installation and methods to fix it.

Regards
Rajesh Kumar.

**What is your host/environment?**
 - OS: Distributor ID: Debian
                                 Description:    Debian GNU/Linux 11 (bullseye)
                                 Release:        11
 - Version : Opensearch 2.2.0
 - Plugins : dashboards-reports 2.2.0.0

**Comment by rupal-bq** [comment]
Hi Rajesh,

dashboard-reports plugin will be already installed with OpenSearch Dashboards [2.2.0.0](https://opensearch.org/versions/opensearch-2-2-0.html) installation.

If you have removed plugins after the installation and trying to reinstall, you can download the tar file, extract and move/copy folder `<Opensearch Dashboards dir>/plugins/reportsDashboards` and `<Opensearch dir>/plugins/opensearch-reports-scheduler`

You can also build dashboard-reports & reports scheduler then move build artifact to plugin directory of Opensearch Dashboard and Opensearch respectively or check for build artifacts in github actions.

**Comment by Rajeshdaneti** [comment]
Hi Rupal,
I am able to see the plugin - reportsDashboards in my opensearch dashboard 2.2.0, dowloaded from opensearch website and installed.But this plugins does not have features like automatic generation through scripts or API, send to email or external destination. My requirement is is that a pdf or csv report be automatically generated by an external system, such as a microservice, by invoking a script or API.
The reason behind installing this plugin -(https://github.com/opensearch-project/dashboards-reports/archive/refs/tags/2.2.0.0.zip) is that  I thought it will provide us additional features , please correct me if I am wrong.

Please assist me how to fulfil my requirement. Is there an open source solution to the problem?

Regards
Rajesh Kumar.

**Comment by rupal-bq** [comment]
Hi Rajesh, Thanks for explaining the use case. These requirements are not supported with plugin at the moment. These  requirements will be supported with Reporting CLI. You can check details [here](https://github.com/opensearch-project/dashboards-reports/issues/345). It isn't released yet but meanwhile if you would like to try it out, please check this [doc](https://github.com/rupal-bq/dashboards-reports/blob/reporting-anything/reporting/docs/dev/DEVELOPER_GUIDE.md). Currently csv isn't added in CLI but we'll add it soon. Also, the report will be downloaded in current directory, we can configure to custom path if your use case requires that.

**Comment by Rajeshdaneti** [comment]
Hi Rupal,
Thank you very much for your support. I have downloaded the zip file and tried to install but getting following error. 
sh-4.2$ cd reporting
sh-4.2$ npm install -g .
npm ERR! Can't install /usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting: Missing package version
npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/share/opensearch-dashboards/.npm/_logs/[2022-12-06T07_52_09_924Z-debug.log](https://github.com/opensearch-project/dashboards-reports/files/10163995/2022-12-06T07_52_09_924Z-debug.log).

opensearch dashboard version - 2.2.0

**Comment by Rajeshdaneti** [comment]
Hi Rupal,
Thank you very much for the support. I tried with above command, some deprecated warnings received. After that I tried to run the generate the report but getting following error -
Please help me to resolve the issue.
  sh-4.2# reporting --url https://localhost/app/dashboards#/view/722b74f0-b882-11e8-a6d9-e546fe2bba5f --format png
fs.js:498
  handleErrorFromBinding(ctx);
  ^
Error: ENOENT: no such file or directory, open '/root/.aws/config'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.readFileSync (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/util.js:95:26)
    at parseFile (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:38)
    at IniLoader.loadFrom (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:72:25)
    at getRegion (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/node_loader.js:131:32)
    at Config.region (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/node_loader.js:186:18)
    at Config.set (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/config.js:600:39)
    at Config.<anonymous> (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/config.js:359:12)
    at Config.each (/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting/node_modules/aws-sdk/lib/util.js:520:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT', 
-----------
Also I tried - npm install aws-sdk  -- Showed  - up to date, audited 437 packages in 1s.

Regards
Rajesh Kumar.

**Comment by rupal-bq** [comment]
Added [fix](https://github.com/opensearch-project/dashboards-reporting/pull/565/commits/710b596751d7e6c6abdc4942236c0d9de1f51ab4) for this issue. Please retry with pulling new changes.
Thanks!

**Comment by Rajeshdaneti** [comment]
Hi Rupal,
Thank you very much for your help.I have downloaded and testing now. I will update you the status.

Regards
Rajesh Kumar.

**Comment by Rajeshdaneti** [comment]
Hi Rupal,
Now , I am able to generate the report. I was facing issue related to chrome.
Fetched argument values
Downloading report failed. Error: Failed to launch the browser process!
/usr/share/opensearch-dashboards/dashboards-reports-reporting-anything/reporting-cli/node_modules/puppeteer-core/.local-chromium/linux-1045629/chrome-linux/chrome: error wh
ile loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory.

Problem is resolved after running below commands -
amazon-linux-extras install epel -y
yum install -y chromium.

However I have some questions, please help me-
1) In document, it is mentioned that we can also generate report for object id (saved report) through below command -
reporting-anything --object-id 7adfa750-4c81-11e8-b3d7-01146121b73d --format pdf.
But I am getting following error -
sh-4.2# reporting --object-id Kz3u64QBun0oheBCcZQK --format pdf
error: unknown option '--object-id'.
2) How to call reporting from external system  such as shell scripts, microservices etc.
3) When generating report, it is saving as reporting.pdf, is it possible to save with name?

Regards
Rajesh Kumar.

**Comment by rupal-bq** [comment]
> 1. In document, it is mentioned that we can also generate report for object id (saved report) through below command -
reporting-anything --object-id 7adfa750-4c81-11e8-b3d7-01146121b73d --format pdf.
But I am getting following error -
sh-4.2# reporting --object-id Kz3u64QBun0oheBCcZQK --format pdf
error: unknown option '--object-id'.

`--object-id` isn't supported. Use `--url` option instead. You can find examples [here](https://github.com/rupal-bq/dashboards-reports/blob/reporting-anything/reporting-cli/docs/user/Reference%20Manual.md)

>  2. How to call reporting from external system such as shell scripts, microservices etc.

Once you have installed the reporting package globally, you can integrate it in your workflow similar to any other cli program.  This isn't documented yet. We will add examples soon.

**Comment by rupal-bq** [comment]
Closing this as the core issue was related to plugin installation. Please feel free to create new issue for further questions related to cli.

**Comment by adit-cmd** [comment]
Hi @rupal-bq .. I have a similar use case. I am fairly new to opensearch and would appreciate your insights on couple of queries I have. Firstly I see the following plugins installed: 

sh-5.2$ /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin list

alertingDashboards@2.13.0.0
anomalyDetectionDashboards@2.13.0.0
assistantDashboards@2.13.0.0
customImportMapDashboards@2.13.0.0
ganttChartDashboards@2.13.0.0
indexManagementDashboards@2.13.0.0
mlCommonsDashboards@2.13.0.0
notificationsDashboards@2.13.0.0
observabilityDashboards@2.13.0.0
queryWorkbenchDashboards@2.13.0.0
reportsDashboards@2.13.0.0
searchRelevanceDashboards@2.13.0.0
securityAnalyticsDashboards@2.13.0.0

As mentioned by Rajesh above I do see "reportsDashboards" as one of the plugins already installed. Can you please briefly explain the use of this plugin?

We already have couple of reports created manually through UI. As of now we have to manually download the reports from UI. I am trying to automate the process of downloading the reports programmatically. We are generating a report for a saved_search. So the below curl works and I see the saved_search title in the output. 

curl -X GET "http://localhost:5601/api/saved_objects/_find?type=search&fields=title&fields=id&per_page=10&page=1"

Now one of the saved_searches has a report and I want to download that report. The format not necessarily needs to be a CSV file. PDF or PNG should work. 

My idea is to download the report using /api/reporting endpoints after finding the report id. How ever when I try to use the /api/reporting endpoint I get the following response. 

sh-5.2$ curl -X GET "http://localhost:5601/api/reporting/_find?per_page=10&page=1" -H "kbn-xsrf: true"
{"statusCode":404,"error":"Not Found","message":"Not Found"}
sh-5.2$

The internet / chatgpt suggests that inorder to interact with the /api/reporting endpoints, I need the reporting plugin. I am confused here. When I listed the above plugins, I saw "reportsDashboards". Is it not the right plugin? 

I have also come across few suggestions where the opensearch_dashboard.yml config file has to be updated with the following entries:

opensearch_dashboards.reporting.enabled: true
opensearch_dashboards.reporting.capture.enabled: true

Appreciate your help in clearing my doubts and confusion. Also could you suggest the most feasible approach for this? My requirement is to download the reports periodically and store the report in object storage like s3.
