### ISSUE TITLE
[BUG] Legend missing on generated reports

### ISSUE THREAD

**Issue by gunzl1ng3r** [opensearch-project/dashboards-reporting#80]
**What is the bug?**
Legend on visualizations is missing in generated report (pdf and png)

**How can one reproduce the bug?**
- Create a dashboard with visualizations (that have the legend enabled)
- generate a report (doesn't matter if pdf or png)
- miss legend :(

**What is the expected behavior?**
- legends are present

**What is your host/environment?**
Opensearch Host
- opensearchproject/opensearch:2.6.0 (same result with 2.5.0)
- opensearchproject/opensearch-dashboards:2.6.0  (same result with 2.5.0)

Client
 - OS: Ubuntu 22.04.2 LTS
 - Version: 22.04.2 LTS
 - Plugins:
     - Edge: none
     - Firefox: uBlock origin
 - tested Browsers:
    - Firefox 110.0.1 (64-Bit)
    - Microsoft Edge 110.0.1587.57 (64-Bit)
    - Chromium 110.0.5481.177
    - Google Chrome 110.0.5481.177

**Do you have any screenshots?**

That is what the dashboard looks like (graphs have legends)
![Dashboard_Edge](https://user-images.githubusercontent.com/6085597/223706095-b1fba131-6dfe-4cc5-8988-153660eb231d.jpg)

And that's what the report generated from that dashboard looks like in FireFox and Edge
![Report_Firefox](https://user-images.githubusercontent.com/6085597/223706107-131fd294-bfda-43c6-a690-d8f25b1e4f89.jpg)
![Report_Edge](https://user-images.githubusercontent.com/6085597/223705888-cd409f62-fdb1-4c26-8814-d87da52493bf.jpg)

**Do you have any additional context?**
In other news: if the Navigation is docked, it is included in the generated reports, which does not feel intuitive

**Comment by joshuali925** [comment]
i'm able to reproduce. we are removing some elements from report, looks like legend was accidentally removed as well. I removed this part and legends were included
https://github.com/opensearch-project/dashboards-reporting/blob/f93e13850ca18ee42e488789717fd04f60ed4a0e/public/components/visual_report/generate_report.ts#L55-L69

i will try to find some time and check how to fix. meantime if you are willing to, feel free to take a look and submit a PR

**Comment by singhankit62000** [comment]
Hi @rupal-bq , do we have these changes effective in the 2.6.0 version or are we going to receive this in the next version?

**Comment by joshuali925** [comment]
@singhankit62000 next version (2.7.0)

**Comment by singhankit62000** [comment]
Okay @joshuali925 thanks! 😊
